version: '3'

services:

  web:
    image: 127.0.0.1:5000/intranet-web
    command: yarn workspace @intranet/web prod
    restart: always

  api:
    image: 127.0.0.1:5000/intranet-api
    command: yarn workspace @intranet/api prod
    restart: always

  puppeteer:
    image: 127.0.0.1:5000/intranet-puppeteer
    command: yarn workspace @intranet/puppeteer prod
    restart: always

  db:
    restart: always

  db-gui:
    restart: always
