version: '3'

services:

  web:
    image: 127.0.0.1:5000/intranet-web
    command: yarn workspace @intranet/web prod
    restart: always
    ports:
      - '80:8080'

  api:
    image: 127.0.0.1:5000/intranet-api
    command: yarn workspace @intranet/api prod
    restart: always

  db:
    restart: always

  db-gui:
    restart: always
