version: '3'

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.web
    command: yarn workspace @intranet/web dev
    volumes:
      - ./packages/frontend/web:/usr/src/app/packages/frontend/web
    ports:
      - '${WEB_PORT}:${WEB_PORT}'

  api:
    command: yarn workspace @intranet/api dev
    volumes:
      - ./packages/backend/api:/usr/src/app/packages/backend/api
    ports:
      - '${DEBUG_PORT}:9229'
