version: '3.9'

services:

  web:
    image: registry.${DOMAIN}/intranet-web
    command: yarn workspace @intranet/web prod
    build:
      context: .
      dockerfile: ./Dockerfile.web
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.intranet-web.service=intranet-web
        - traefik.http.routers.intranet-web.entrypoints=web
        - traefik.http.routers.intranet-web.rule=Host(`${DOMAIN:-localhost}`)
        - traefik.http.services.intranet-web.loadbalancer.server.port=${WEB_PORT:-8080}
      restart_policy:
        condition: on-failure
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
    networks:
      - public

  api:
    image: registry.${DOMAIN}/intranet-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile.api
    command: yarn workspace @intranet/api prod
    volumes:
      - intranet_api_tmp:/usr/src/app/packages/backend/api/tmp
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.intranet-api.service=intranet-api
        - traefik.http.routers.intranet-api.entrypoints=web
        - traefik.http.routers.intranet-api.rule=(Host(`${DOMAIN:-localhost}`) && PathPrefix(`/gateway`))
        - traefik.http.routers.intranet-api.middlewares=intranet-api-redirectregex, intranet-api-replacepathregex
        - traefik.http.middlewares.intranet-api-replacepathregex.replacepathregex.regex=^/gateway/(.*)
        - traefik.http.middlewares.intranet-api-replacepathregex.replacepathregex.replacement=/$$1
        - traefik.http.middlewares.intranet-api-redirectregex.redirectregex.regex=^(.*)/gateway$$
        - traefik.http.middlewares.intranet-api-redirectregex.redirectregex.replacement=$$1/gateway/
        - traefik.http.services.intranet-api.loadbalancer.server.port=${API_PORT:-3333}
      restart_policy:
        condition: on-failure
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
    depends_on:
      - db
    networks:
      - public
      - backend

  db:
    image: bitnami/mariadb:10.5.15
    hostname: ${MYSQL_HOST:-db}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${MYSQL_PASS:-docker}
      - MARIADB_USER=${MYSQL_USER:-mysql}
      - MARIADB_PASSWORD=${MYSQL_PASS:-docker}
      - MARIADB_DATABASE=${MYSQL_DB:-intranet}
    volumes:
      - db_data:/bitnami/mariadb
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

  db-gui:
    image: phpmyadmin/phpmyadmin:5.1.3
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=http://intranet.tiasonia.com.br/phpmyadmin
    depends_on:
      - db
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.mysql-gui.service=mysql-gui
        - traefik.http.routers.mysql-gui.entrypoints=web
        - traefik.http.routers.mysql-gui.rule=(Host(`${DOMAIN:-localhost}`) && PathPrefix(`/phpmyadmin`))
        - traefik.http.routers.mysql-gui.middlewares=mysql-gui-redirectregex, mysql-gui-replacepathregex
        - traefik.http.middlewares.mysql-gui-replacepathregex.replacepathregex.regex=^/phpmyadmin/(.*)
        - traefik.http.middlewares.mysql-gui-replacepathregex.replacepathregex.replacement=/$$1
        - traefik.http.middlewares.mysql-gui-redirectregex.redirectregex.regex=^(.*)/phpmyadmin$$
        - traefik.http.middlewares.mysql-gui-redirectregex.redirectregex.replacement=$$1/phpmyadmin/
        - traefik.http.services.mysql-gui.loadbalancer.server.port=80
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
    networks:
      - backend
      - public

volumes:
  db_data: {}
  intranet_api_tmp: {}

networks:
  backend:
    name: backend
    driver: overlay
  public:
    external: true

